#!/system/bin/sh
#
# kernelLoad
#  -Derrived from Tortel's "change_kernel.sh" script.
# nubecoder 2012 - http://www.nubecoder.com/
#

#functions
SHOW_HELP()
{
	echo "=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]"
	echo "Usage: $0 <kexec path> <zImage path>"
	echo "=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]=]"
	exit 1
}

KEXEC_BOOT_ZIMAGE()
{
	local KEXEC_FILE="$1"
	local ZIMAGE_FILE="$2"
	busybox chmod 777 "$ZIMAGE_FILE"
	busybox mount -ro remount /dev/block/stl6 /mnt/.lfs
	busybox mount -ro remount /dev/block/stl9 /system
	busybox mount -ro remount /dev/block/stl10 /data
	busybox mount -ro remount /dev/block/stl11 /cache
	# normal boot
	$KEXEC_FILE --load-hardboot --mem-min=0x50000000 --append="console=ttySAC2,115200 loglevel=4 no_console_suspend=1" "$ZIMAGE_FILE"
	# recovery boot
	#/sbin/kexec --load-hardboot --mem-min=0x50000000 --append=bootmode=2 "$FILE"
	sync
	$KEXEC_FILE -e
}

#main
if busybox test -x "$1" && busybox test -f "$2" ; then
	KEXEC_BOOT_ZIMAGE "$1" "$2"
fi

SHOW_HELP

