#!/bin/bash
#
# includes
# nubecoder 2012 - http://www.nubecoder.com/
#

#defines
KBUILD_BUILD_VERSION="nubernel-2.6.35_v0.0.2"
LOCALVERSION=".nubernel_v0.0.2"
VERSION_PATH="lib/modules/2.6.35.13+"

KERNEL_BASE="/home/nubecoder/android/projects/SPH-D700/kernel/2.6.35"
CROSS_COMPILE="/home/nubecoder/android/toolchains/arm-eabi-4.4.3/bin/arm-eabi-"
CC_STRIP="${CROSS_COMPILE}strip -d --strip-unneeded"

TARGET_TW="victory_nubernel"
TARGET_MTD="victory_nubernelmtd"
TARGET_CM7="cyanogenmod_epicmtd"
TARGET_MOD="victory_modules"
TARGET_BML8="victory_bml8mtd"

INSTALL_MOD_PATH="$KERNEL_BASE/res/modules"
INITRAMFS_TW_PATH="$KERNEL_BASE/initramfs/tw"
INITRAMFS_MTD_PATH="$KERNEL_BASE/initramfs/mtd"
INITRAMFS_CM7_PATH="$KERNEL_BASE/initramfs/cm7"
MODULES_CM7_PATH="$KERNEL_BASE/update/cm7"

RES_BIN_PATH="$KERNEL_BASE/res/bin"
RES_SCRIPTS_PATH="$KERNEL_BASE/res/scripts"

DEVICE_TMP_PATH="/data/local/tmp"

BUILT_ZIMAGE="$KERNEL_BASE/Kernel/arch/arm/boot/zImage"
BUILT_BOOTIMAGE="$KERNEL_BASE/res/mtd/boot.img"

ZIMAGE_SRC="$BUILT_ZIMAGE"
KERNELLOAD_SRC="$RES_SCRIPTS_PATH/kernelLoad"
KEXEC_SRC="$RES_BIN_PATH/kexec"

ZIMAGE_DEST="$DEVICE_TMP_PATH/zImage"
KERNELLOAD_DEST="$DEVICE_TMP_PATH/kernelLoad"
KEXEC_DEST="$DEVICE_TMP_PATH/kexec"

ADB_KERNEL_LOAD="su -c \"$KERNELLOAD_DEST $KEXEC_DEST $ZIMAGE_DEST\""

ADB_KILL="adb kill-server"
ADB_CONNECT="adb connect"
ADB_DISCONNECT="adb disconnect"
ADB_SHELL="adb shell"
ADB_PUSH="adb push"
ADB_STATE="adb get-state"

THREADS=$(expr 1 + $(grep processor /proc/cpuinfo | wc -l))
VERSION=${KBUILD_BUILD_VERSION}_$(date +%m-%d-%Y)
ERROR_MSG=
TIME_START=
TIME_END=

#source functions
source "$KERNEL_BASE/include/functions"

